# only includes cleaning, peeling, and slicing activities for potentially simpler training
devices:
  myo-left:
    stream: emg
    cutoff_freq: 1
    absolute_value: True
    normalize_offset: 1
    normalize_scale: 99
  myo-right:
    stream: emg
    cutoff_freq: 1
    absolute_value: True
    normalize_offset: 1
    normalize_scale: 99
  tactile-glove-left:
    stream: tactile_data
    cutoff_freq: 1
    absolute_value: False
    normalize_offset: 1
    normalize_scale: 99
  tactile-glove-right:
    stream: tactile_data
    cutoff_freq: 2
    normalize_offset: 1
    absolute_value: False
    normalize_offset: 1
    normalize_scale: 90
activities: "Clean a plate with a towel|Peel a potato|Peel a cucumber|Clean a pan with a towel|Slice a potato|Clean a pan with a sponge|Slice a cucumber|Slice bread|Clean a plate with a sponge"
sampling_freq: 50.0