name: traj-gen
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.12
  - attr=2.5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.9.24
  - cached-property=1.5.2
  - cairo=1.18.0
  - clarabel=0.7.1
  - cmake=3.30.5
  - contourpy=1.2.0
  - cvxpy=1.5.3
  - cvxpy-base=1.5.3
  - cycler=0.11.0
  - dbus=1.13.18
  - ecos=2.0.12
  - eigen=3.4.0
  - expat=2.6.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.82.1
  - glib-tools=2.82.1
  - graphite2=1.3.14
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h5py=3.12.1
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - icu=75.1
  - intel-openmp=2022.0.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.69
  - libclang-cpp15=15.0.7
  - libclang13=19.1.1
  - libcups=2.3.3
  - libcurl=8.10.1
  - libdeflate=1.22
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=8.2.0
  - libgfortran5=14.1.0
  - libgl=1.7.0
  - libglib=2.82.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.1.0
  - libgpg-error=1.50
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libllvm19=19.1.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopus=1.3.1
  - libosqp=0.6.3
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=16.4
  - libqdldl=0.1.7
  - libsndfile=1.2.2
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=256.7
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libuv=1.49.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=19.1.0
  - lxml=5.3.0
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpg123=1.32.6
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nspr=4.35
  - nss=3.105
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - osqp=0.6.7.post0
  - packaging=24.1
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - ply=3.11
  - pthread-stubs=0.3
  - pulseaudio-client=17.0
  - pybind11-abi=5
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.12.7
  - python-dateutil=2.9.0post0
  - python_abi=3.12
  - pyyaml=6.0.2
  - qdldl-python=0.1.7.post0
  - qt-main=5.15.8
  - quaternion=2024.0.2
  - readline=8.2
  - rhash=1.4.4
  - scipy=1.13.1
  - scs=3.2.7
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.46.1
  - tbb=2021.8.0
  - tk=8.6.13
  - tornado=6.4.1
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wheel=0.44.0
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.11
  - xorg-libxxf86vm=1.1.5
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xorgproto=2024.1
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.6
